<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<RootNamespace>MC_ModManager</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ini-parser-netstandard" Version="2.5.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="Tomlyn" Version="0.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helper\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

</Project>
